#Build Stage

FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum

COPY . >

RUN go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

#Run stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8000

CMD ["./main"]